- .github/workflows/sdk-generation.yaml
- .github/workflows/sdk-publish.yaml
Add `smorimoto/tune-github-hosted-runner-network` to all jobs as a pre-step, to attempt to reduce the network problems observed on github hosted action runners.
> fix: flaky network calls on github hosted action runners

- action.yml
- internal/actions/validate.go
- internal/cli/cli.go
- internal/cli/speakeasy.go
- internal/git/git.go
- internal/suggestions/suggestion.go
- testing/suggestion-test.sh
- testing/suggestions.env
Adds LLM suggestions as a github action feature which can create a PR with suggestions.
This runs off of the validate action. The only additional variables a developer would need to add are
speakeasy CLI > 1.47.1
inputs.openai_api_key=
inputs.write_suggestions="true"
> feat: Suggestion Action Scaffold

- action.yml
- internal/actions/generate.go
- internal/actions/validate.go
- internal/environment/environment.go
Need to release to test.
Also, makes `OPENAI_API_KEY` optional. Didn't catch it in an earlier review, but we shouldn't require this to be passed in.
> feat: add action input to change working directory for validate/generate steps

- internal/actions/validate.go
- internal/document/document.go
Allows us to support remote documents in the suggestion action. This will display the suggestion in a temp file openapi_{0}
> feat: support remote documents in suggestion action

- .github/workflows/sdk-generation.yaml
- .github/workflows/sdk-publish.yaml
- README.md
This is necessary to properly generate workflow files
> fix: match java gpg passphrase name between actions

- internal/actions/validate.go
- internal/cli/cli.go
- internal/environment/environment.go
The limits are user-configurable via INPUT_MAX_VALIDATION_WARNINGS and INPUT_MAX_VALIDATION_ERRORS inputs.
> feat: limit warn/err output to 1000 each by default

- internal/git/diff.go
- internal/git/diff_test.go
This change ensures files that use tabs (`\t`) for spacing are correctly scanned for significant changes. This was affecting Go SDKs in particular. Additionally, it updates the action to ignore changes to version and user-agent info in source files since these are explicitly insignificant changes.
> fix: detect significant changes in `.go` files

- internal/actions/generate.go
- internal/cli/cli.go
- internal/document/document.go
Modification of base directory seemed to effect the output. This moves the overlayed file to always be in the same base directory as other overlay files. 
This also removes assumptions on the current working directory by ensuring that the absPath of overlays/resolved openapi files is passed into the speakeasy binary as an argument
> fix: overlay implementation

- internal/generate/generate.go
- internal/git/diff.go
- internal/git/diff_test.go
- internal/git/git.go
Not as clever as a version number string canary; but didn't want to do multiple passes through generation.
> fix: discover version number changes (and ignore them) even when in an unusual location

- .github/action-inputs-config.json
Turns out we aren't handling this correctly yet. So just remove it for now so we can ship the other bit
> fix: remove dotnet version from config definition

- internal/cli/cli.go
To merge after this CLI is [released](https://github.com/speakeasy-api/speakeasy/pull/349)
Again technically this would be backwards incompatible if it was used frequently in the wild but given we are mostly setting up the docs action manually right now we can make this change now.
> feat: put docs command under generate

- internal/git/git.go
Currently, if an action is pinned to an old release of the CLI, we might not find on it and erroneously fail. This is because we only check the first page of results from github (30). This PR adds functionality to check all pages of results before failing  ([thread](https://speakeasyapi.slack.com/archives/C03PU4G2FDL/p1704410807967609))
> fix: iterate through all releases to try to find the right version

- .github/workflows/sdk-generation.yaml
`dotnet format` is only supported in v 6+
> fix: run correct c# build command

- Dockerfile
This PR changes the docker base image to 3.18 and installs `libssl1.1`
Note: `openssl1.1-compat` [is needed](https://github.com/speakeasy-api/action-v15-test/actions/runs/8011141817/job/21883691588#step:4:327) for compiling with .NET5 but is [not available in golang:1.21-alpine (3.19)](https://gitlab.alpinelinux.org/alpine/aports/-/issues/15575).
> fix: install libssl1 for .NET5 compilation

- internal/actions/log.go
This will be a start. We will at least get the full error message with our failure logs.
Not as ideal as us just getting native datadog logging from github actions, but we still have some stuff to figure out there.
> feat: error message in github actions log proxy

- internal/telemetry/telemetry.go
The success status of a target is determined by if all the cli_events for a particular execution ID are successful. If the execution ID does not change between runs the target will always appear failed even if it succeeds when manually re-running the action.
> fix: execution ID should be unique to each GitHub run attempt

- internal/actions/finalize-suggestion.go
- internal/actions/runWorkflow.go
- internal/git/git.go
The goal of this change is to reset PR branches instead of adding to them, such that SDK PRs don't grow endlessly (and their versions along with it)
> feat: reset PR branches rather than appending

- internal/git/git.go
https://linear.app/speakeasy/issue/SPE-3270/bug-with-creating-prs-due-to-recent-addition-of-workflowlock-will
> fix: ignore workflow.lock when checking dirtiness

- internal/git/fixtures/README.md
- internal/git/fixtures/nested/names.txt
- internal/git/fixtures/sample.txt
- internal/git/git.go
- internal/git/git_test.go
This change removes an inner loop introduced in `CheckDirDirty` that was not correctly skipping over files we should be ignoring when doing dirty checks of a working directory.
> fix: remove buggy inner loop from git dirty check

- .github/workflows/workflow-executor.yaml
- action.yml
- internal/cli/run.go
- internal/cli/speakeasy.go
- internal/environment/environment.go
Support passing in tags as an input to sdk-generation-action as discussed in this [RFC](https://www.notion.so/speakeasyapi/RFC-Thoughts-on-Tagging-One-Pager-2f0dcfd18f0d47d98e9b7c2e2b1f439f?pm=c)
Here's an example of a few different tag input formats that we can simultaneously support. These are all tested and they work.
- [Most readable](https://github.com/ryan-timothy-albert/sample-spec-workflow/blob/47d0c908f3197603b4468c88877ae7bffc2e642a/.github/workflows/sdk_generation.yaml)
- [Single Line](https://github.com/ryan-timothy-albert/sample-spec-workflow/blob/94d5af8fa65b47b1896e2bf9963f89f15494b36c/.github/workflows/sdk_generation.yaml)
- [Advanced Usecases](https://github.com/ryan-timothy-albert/sample-spec-workflow/blob/a649eb949b4d6df58e313c0e43a5b21df9142b04/.github/workflows/sdk_gen …
> feat: registry tags in action input

- internal/actions/utils.go
The releases directory needs to be set to the output directory when supporting separated monorepo generation
> feat: correctly set releases dir in monorepo mode

- .github/workflows/sdk-publish.yaml
- action.yml
- go.mod
- go.sum
- internal/actions/publishEvent.go
- internal/environment/environment.go
- main.go
Start sending publishing CLI events for dashboard visualization even though publishing itself doesn't go through the CLI.
I implemented this for PYPI first. Once we are good with approach will extend it to more package managers. We can also add more event metadata overtime as we want more. We should always have access to gen lock and gen files.
> feat: add publishing CLI events support python

- .github/workflows/sdk-publish.yaml
- .github/workflows/workflow-executor.yaml
- internal/actions/publishEvent.go
Adds support for publishing events for 
PYPI
NPM
Packagist
Nuget
Gems
Terraform
Sonatype
in both PR and direct mode
> feat: add support for more publishing events

- Dockerfile
SPE-3381: install .NET8.0 alongside .NET5.0 and .NET6.0
Tested inside local container:
```
$ which dotnet
/usr/bin/dotnet
$ dotnet --version
8.0.300
$ dotnet --list-sdks
5.0.408 [/usr/lib/dotnet/sdk]
6.0.125 [/usr/lib/dotnet/sdk]
8.0.300 [/usr/lib/dotnet/sdk] 
```
> feat: add support for .NET8.0

- .github/workflows/workflow-executor.yaml
- Makefile
- action.yml
- internal/actions/runWorkflow.go
- internal/environment/environment.go
- testing/push-code-samples-only.env
This will generate code samples, tag them with the `main` branch name, and push them to the registry. It will not create a pull request or commit any code. This is useful for pushing up some code samples to the registry the first time when there are no code samples in the registry. This is for the Mintlify Integration.
> feat: populate code samples in the registry

- .github/workflows/sdk-publish.yaml
- .github/workflows/workflow-executor.yaml
SPE-3470
`dotnet pack` uses `Debug` configuration by default.
Should be merged alongside: https://github.com/speakeasy-api/openapi-generation/pull/1301
to avoid building the project twice
> fix: set dotnet pack configuration to Release when publishing to NuGet

- .github/workflows/tag.yaml
> fix: require gh_access_token in tagging action

- pkg/releases/releases.go
the `-` is disallowed in a pep 440 compliant prerelease version. We should be able to read without `-` for python
> chore: support pep440 compliant pypi prereleases

- .github/workflows/sdk-publish.yaml
- .github/workflows/tag.yaml
- .github/workflows/workflow-executor.yaml
- action.yml
- internal/actions/utils.go
- internal/configuration/configuration.go
- internal/git/git.go
- internal/run/run.go
We currently do not support placing your .speakeasy folder not in the root directory of a github repo. We need to support this less common usecase for some customers coming in.
To do this we ensure that the usage of the existing `working_directory` input. 
We actually don't use github actions run.working-directly because
1. This can't be used from uses which invokes our docker image
2. We actually don't want to change the entire directory away from root. Just the context of using speakeasy run
> feat: allow non root working dir in run

- .github/workflows/workflow-executor.yaml
This change populates a missing input to correctly setup dotnet for C# publishing in direct mode
> fix: C# Publishing when running in `direct` mode

- .github/workflows/workflow-executor.yaml
- Dockerfile
- action.yml
- internal/actions/runWorkflow.go
- internal/actions/setup_environment.go
- internal/environment/environment.go
This input enables pnpm to be globally installed into the Docker runtime. It is not recommended for use without consulting Speakeasy support.
> feat: Support pnpm_version input

- go.mod
- go.sum
This change is safe, but given we don't need to bump it anymore right now I would rather stage changes and not move forward a bunch of versions while we are changing other publishing things
> feat: revert sdk gen config bump

- .github/workflows/workflow-executor.yaml
- internal/actions/runWorkflow.go
- internal/run/run.go
If the CLI uses a specific speakeasyVersion and generationVersion to generate the SDK. That needs to be propogated back to Github so logs and releases entries are correct. The CLI determines what specific version is used to generate via workflow.yaml, not github.
> feat: propogate CLI/Generation version from what was used by the CLI

- go.mod
- go.sum
- internal/actions/runWorkflow.go
- internal/telemetry/telemetry.go
Collects the GitHub PR URL (when applicable) and adds it to the event telemetry (again when applicable).
> feat: track GitHub PRs in CLI events

- internal/actions/runWorkflow.go
- internal/git/git.go
- main.go
1. Stop sending a CI_EXEC cli_event when we are just performing telemetry logs or sending a publishing event. It unnecessarily pollutes cli_events.
2. There was an issue with gh_pull_request in CLI Events. Looks like we weren't capturing new PRs.
> chore: small action improvements

- internal/telemetry/telemetry.go
Noticing PR URLs are coming back from GH Actions in the following format `https://api.github.com/repos/ryan-timothy-albert/test_nested_repo/pulls/27`
> feat: format pull request link

- .github/workflows/workflow-executor.yaml
- action.yml
- internal/actions/runWorkflow.go
- internal/cli/cli.go
- internal/cli/run.go
- internal/environment/environment.go
- internal/git/git.go
- internal/git/git_test.go
- internal/git/labels.go
- internal/run/run.go
- internal/versionbumps/versionBumps.go
Discussed a while with @ThomasRooney quite a few different things we need to think about for this feature
- Because we add version labels to PRs if someone is triggering generation off of label added this could lead to duplicate generations potentially even an infinite loop. This is taken care of by PR body record being different from the version label applied
- If someone manually sets a version bump label and that does not align with what is in the PR body we will generate with that version bump label.
- If we set the bump type label. We don't want to stick on that bump type for ever. The SDK could evolve if the PR is left open for a long time. This is why we will utilize the [Automated] marking in PR body. 
- If someone manually sets a version bump label we will allow them to stay on …
> feat: support label based versioning

- .github/workflows/sdk-publish.yaml
- .github/workflows/workflow-executor.yaml
Downgrade the default github runner image to 22.04 due to observed failings of .NET publishing in the 24.04 rollout.
> chore: downgrade default runs-on

- .github/workflows/sdk-publish.yaml
- .github/workflows/workflow-executor.yaml
- Dockerfile
- action.yml
- internal/actions/setup_environment.go
- internal/environment/environment.go
Reference: https://linear.app/speakeasy/issue/GEN-877/tech-debt-python-poetry-20
This change adds a `poetry_version` input to each of the workflows to specify the Poetry tool version to install and use. By default, the latest (2.0.0 as of this change) is installed, but this is being added as a compatibility layer for calling GitHub Actions workflows that pin the Speakeasy CLI to an older version, which require an older Poetry version before the major version update such as 1.8.3.
This change also bumps Python from 3.8 (EOL since October 2024) to 3.9 (required for Poetry 2.0.0) for publishing workflows.
> feat: Support poetry_version input to specify Poetry tool version

- .github/workflows/test.yaml
- Dockerfile
Reference: https://speakeasyapi.slack.com/archives/C06AT209C5A/p1736455295374799?thread_ts=1736445206.094809&cid=C06AT209C5A
> fix: Remove unsupported openssl1.1-compat and .NET 5 (for Unity) from Docker image and add CI

- internal/actions/setup_environment.go
Otherwise, `pipx install` binaries are not on the PATH for generator commands.
> fix: Ensure pipx install is global

- .github/workflows/workflow-executor.yaml
- action.yml
- internal/cli/run.go
- internal/environment/environment.go
Reference: https://linear.app/speakeasy/issue/GEN-780/feature-sdk-generation-action-skip-target-testing-input
Set to true to explicitly skip Speakeasy workflow target testing after generation, even when enabled in the Speakeasy workflow configuration. This is useful for running workflow testing as a separate GitHub Actions workflow without affecting/blocking generation. It can also be used to workaround potential testing bugs where the generation should still be preserved.
> feat: Support skip_testing input to explicitly skip target testing

- .github/workflows/workflow-executor.yaml
- Dockerfile
- action.yml
@ryan-timothy-albert 
Here's the output from docker build:
```
(1/19) Installing php83-common (8.3.15-r0)
(2/19) Installing php83-ctype (8.3.15-r0)
(3/19) Installing php83-curl (8.3.15-r0)
(4/19) Installing libxml2 (2.12.7-r0)
(5/19) Installing php83-dom (8.3.15-r0)
(6/19) Installing php83-iconv (8.3.15-r0)
(7/19) Installing oniguruma (6.9.9-r0)
(8/19) Installing php83-mbstring (8.3.15-r0)
(9/19) Installing php83-openssl (8.3.15-r0)
(10/19) Installing argon2-libs (20190702-r5)
(11/19) Installing libedit (20240517.3.1-r0)
(12/19) Installing php83 (8.3.15-r0)
(13/19) Installing php83-phar (8.3.15-r0)
(14/19) Installing php83-tokenizer (8.3.15-r0)
(15/19) Installing php83-xml (8.3.15-r0)
(16/19) Installing php83-xmlwriter (8.3.15-r0)
(17/19) Installing php82-common (8.2.27-r0)
(18/19) …
```
> fix: add php session extension

- .github/workflows/workflow-executor.yaml
- action.yml
- internal/environment/environment.go
- internal/git/git.go
- testing/pr-mode.env
When the `signed_commits` feature flag is enabled, commits will be commited using the GitHub API allowing our bot's committed to be `verified`.
> feat: Add ability to sign commits when flag is enabled

- .github/workflows/sdk-publish.yaml
- .github/workflows/tag.yaml
- .github/workflows/workflow-executor.yaml
- action.yml
- internal/actions/release.go
Update the php publish to checkout the repo, and read the packagename from the composer.json file.  Pass the repository information, but no packageName.
> feat: php publish fix

- .github/workflows/sdk-publish.yaml
- .github/workflows/workflow-executor.yaml
Reference: https://linear.app/speakeasy/issue/GEN-1354/tech-debt-bump-ruby-minimum-version-to-31-or-32
> chore: Upgrade Ruby in workflows to 3.2

- internal/actions/test.go
Previously was only installed in `run-workflow`/`""` action input. Without this, Python targets will receive errors such as:
```
WARN    cannot test target - Dependency Not Found - Install Poetry by following the instructions at https://python-poetry.org/docs/#installing-with-pipx.
INFO    Shutting down mock server
Error: error running tests for target xxx (python): dependency not found -- poetry: exec: "poetry": executable file not found in $PATH
Failed to run with Speakeasy version 1.540.1: failed to run with version 1.540.1: exit status 1
```
> fix: Ensure poetry is installed in test mode

- .github/workflows/sdk-publish.yaml
- .github/workflows/workflow-executor.yaml
Reference: https://linear.app/speakeasy/issue/GEN-1437/feature-update-runs-on-input-to-accept-group-format-in-github-action
Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype
GitHub does not accept non-primitive types for workflow_call event inputs, so this introduces JSON string parsing. This should enable callers to pass any job `runs-on` compatible data, such as:
* string: `runs-on: ubuntu-latest`
* array: `runs-on: '["ubuntu", "example"]'`
* object: `runs-on: '{"group": "example"}'`
> feat: Support JSON string syntax for runs-on input

- go.mod
- go.sum
- internal/run/run_test.go
Reference: https://linear.app/speakeasy/issue/GEN-1670/firehydrant-mcp-not-publishing
Reference: https://github.com/speakeasy-api/sdk-gen-config/pull/85
Currently failing as sdk-gen-config requires update to support `mcp-typescript` target for NPM publishing:
```
--- FAIL: TestAddTargetPublishOutputs (0.00s)
--- FAIL: TestAddTargetPublishOutputs/mcp-typescript-publishing (0.00s)
/Users/bflad/src/github.com/speakeasy-api/sdk-generation-action/internal/run/run_test.go:222: expected map[publish_mcp_typescript:true], got map[publish_mcp_typescript:false]
```
> fix: Ensure mcp-typescript target correctly sets publish_mcp_typescript output if NPM is configured

- .github/workflows/sdk-publish.yaml
- .github/workflows/workflow-executor.yaml
Fixes the case where the previous version was the official/latest version, but the current version we want to use to generate the package is a prerelease. This would result in the alpha version being incorrectly recognized as the official version.
**Current status:**
See that the alpha version was recognized as official version
https://github.com/criblio/cribl-control-plane-sdk-typescript/actions/runs/16901476071/job/47881434070
**Status from PR:**
Here is the proof that it works as expected:
https://github.com/criblio/cribl-control-plane-sdk-typescript/actions/runs/16908940172/job/47905334957
> Use local package.json version instead of registry version

- .github/workflows/sdk-publish.yaml
- .github/workflows/workflow-executor.yaml
Reference: https://docs.gradle.org/9.0.0/release-notes.html#jvm-17
Gradle 9.0.0 is being deployed to GitHub Actions runner images. This new version is incompatible with Java 11 and can return errors such as:
> Gradle requires JVM 17 or later to run. Your build is currently configured to use JVM 11.
This change uses `gradle/actions/setup-gradle` to install Gradle 8.14 and ensure compatibility. If/when Gradle 9.0.0 support is necessary, the workflows may need new inputs for Java/Gradle versions or some additional toolchain/wrapper configuration.
> fix: Explicitly install and use Gradle 8.14 for Java 11 compatibility

- internal/git/git.go
We were incorrectly filtering out commits (commited by speakeasy). A cherry-pick will still be commited by speakeasybot, but the author will be someone else.
> fix: recognize only speakeasy authored commits

- .gitignore
- internal/git/git.go
We weren't resetting the local index(staging area) as part of the signed commits flow that prevented subsequent checkout steps from suceeding.
The signed commit flow roughly looks like this:
- Stage files using a local `git add .`
- Perform a signed commit:
- Create a Tree object in the Git database [using the GH API](https://docs.github.com/en/rest/git/trees?apiVersion=2022-11-28#create-a-tree). We loop over staged files and include relevant entries in the tree.
- Create a commit [referencing the tree SHA](https://github.com/speakeasy-api/sdk-generation-action/blob/main/internal/git/git.go#L655). This is transparently a signed commit since GitHub automatically signs commits made by GitHub Apps with GitHub's own signing key.
We then checkout to the target branch within the finalize step …
> fix: reset worktree in signed commits flow
