speakeasy-api/sdk-generation-action

- .github/workflows/sdk-generation.yaml
- .github/workflows/sdk-publish.yaml
- README.md
- action.yml
https://hub.docker.com/r/speakeasysagar/sdk-generation-action/tags
> feat: Use dockerhub image for faster execution

- action.yml
Missed a spot 🙄 
Praying I don't need to do a whole new release?
> Update action to use v11

- README.md
Not 100% sure this belongs here but thought it would be worthwhile to jot down
> Add java publishing instructions to readme

- internal/git/diff.go
https://speakeasyapi.slack.com/archives/C036B83TW3X/p1680290822014389
> fix: skip git diff check if force generated

- .github/workflows/sdk-generation.yaml
- .github/workflows/sdk-publish.yaml
- action.yml
> chore: for some testing use-cases, allow speakeasy_server_url modification

- .github/workflows/sdk-generation.yaml
not sure how this made it live
> fix: workflow file error missing types

- .github/workflows/sdk-publish.yaml
Fixes [this error](https://github.com/speakeasy-sdks/hookdeck-go/actions/runs/5531151521/workflow)
> fix: only needs release

- .github/workflows/sdk-suggestion.yaml
- action.yml
We are making openai key not required
> feat: comments around using our OpenAI Key usage

- .github/workflows/sdk-docs-generation.yaml
- action.yml
- internal/actions/finalizeDocs.go
- internal/actions/generateDocs.go
- internal/actions/utils.go
- internal/cli/cli.go
- internal/environment/environment.go
- internal/generate/generate.go
- internal/git/git.go
- main.go
- testing/sdk-docs.env
- testing/test.sh
We will follow similar patterns to the sdk action but this action will be a little simpler
- Support PR Mode
- Support Direct Mode
- Validate the spec before docs generation
- Compile docs before finalizing
> feat: add sdk docs generation workflow

- .github/action-inputs-config.json
- .github/action-security-config.json
This is necessary for the webapp to properly create workflow files
> chore: add missing action input/secrets to config json

- .github/actionconfig.go
This file currently does not compile
> fix: fix compilation errors

- .github/workflows/sdk-generation.yaml
- .github/workflows/sdk-publish.yaml
- action.yml
Minor cleanup of names and descriptions
> chore: better java publishing step names

- internal/git/git.go
> feat: V15 explain workflow perms

- internal/actions/log.go
- internal/cli/speakeasy.go
- internal/telemetry/telemetry.go
- testing/test.sh
Also changed `sdk-generation-action-test-repo`
> chore: get tests working again

- .github/workflows/workflow-executor.yaml
> fix: no more sonatype_central

- .github/workflows/tag.yaml
- action.yml
- internal/actions/tag.go
- internal/cli/run.go
- internal/cli/speakeasy.go
- internal/environment/environment.go
- internal/registry/tags.go
- main.go
To be used to add tags to codeSamples (or schemas) on merge to main
Relies on new `speakeasy tag promote` command
> feat: registry tagging action

- internal/git/git.go
https://linear.app/speakeasy/issue/SPE-3736/failed-to-generate-typescript-sdk-due-to-an-error-when-pushing-changes
> chore: improve protected branch error message

- .github/workflows/workflow-executor.yaml
- action.yml
- go.mod
- go.sum
- internal/cli/run_test.go
- internal/cli/speakeasy.go
- internal/environment/environment.go
https://linear.app/speakeasy/issue/SPE-4094/feature-support-interpolated-spec-paths-on-workflows-v15
> chore: support passing arbitrary env vars to speakeasy cli

- Dockerfile
https://wiki.alpinelinux.org/wiki/GCC
https://speakeasyapi.slack.com/archives/C0698C9K4NL/p1726765870914259
> chore: add GCC to docker image

- Dockerfile
Also removes "gcc", something a customer requested last week but didn't actually need
> chore: add pnpm into docker image

- internal/actions/release.go
Want to get this change out quick so we don't attempt to publish on a workflow dispatch if publishing is not setup. Very niche case
> feat: workflow dispatch protect

- internal/actions/release.go
- internal/git/releases.go
- internal/utils/package.go
- internal/utils/package_test.go
track all failed releases in publishing events discussion from publishing recap
> feat: track failed releases as interaction_type: publish

- .github/workflows/workflow-executor.yaml
- action.yml
- internal/git/git.go
- internal/git/labels.go
- internal/versionbumps/versionBumps.go
- We don't recommend having a trigger on `unlabeled` given it might just lead to extraneous action runs, but this will make sure it works if someone chooses to add that.
- Add a custom label when someone manually does a custom version
> feat: small improvements label based versioning

- Makefile
- docker-compose.yaml
- testing/test.sh
Fix up the tests to run in a docker instead of on the local machine; simply run `make test-*`
> Move tests to run in the docker container instead of on the local machine

- go.mod
- go.sum
- internal/environment/environment.go
- internal/environment/environment_test.go
- internal/git/git.go
- internal/git/git_test.go
This PR implements source-branch-aware SDK generation to resolve conflicts between multiple generations from different source branches. Previously, all SDK generations used shared branch naming and PR titles, causing the last generation to overwrite previous ones.
**Before**: Multiple SDK generations from different source branches would conflict:
- All used same branch naming pattern (`speakeasy-sdk-regen-{timestamp}`)
- All PRs had identical titles, causing conflicts
- Last generation would overwrite previous ones
- All PRs targeted main/master regardless of source
**After**: Each source branch gets its own dedicated generation:
- Feature branches: `speakeasy-sdk-regen-{source-branch}-{timestamp}`
- PR titles include source context: `chore: 🐝 Update SDK [feature-branch]`
- PRs target the …
> feat: implement source-branch-aware SDK generation to prevent conflicts
